### PR TITLE
use os.linesep for line separation for compatibility with non-windows systems

### PR DESCRIPTION
**Pull request by chaotika**
… systems

### CODE REVIEW

**Comment by chaotika** [comment]
Fixes #3

**Comment by chaotika** [comment]
I added a keyword to the save function so the line ending format can be specified when needed.

**Comment by chaotika** [comment]
I was motivated and also included the newline detection feature.

**Comment by vonshednob** [comment]
I'd add you to the authors, but you can also add youself already, if you want that!

**Comment by chaotika** [comment]
> I'd add you to the authors, but you can also add youself already, if you want that!

Yeah sure, Authors or Contributers?

**Comment by vonshednob** [comment]
> Yeah sure, Authors or Contributers?

`AUTHORS` file, Contributors section. Thanks a lot!

**Comment by chaotika** [comment]
In 54f0dad i handle the case when multiple newline separators are detected so that when the OS newline seperator has been used in the source file it uses the system default newline separator, otherwise if the newline seperator of the OS has not been used in the source file but other ones it use the first found newline separator. 

This is the behavior i would expect. This could happen when you add something to the file on a system with `echo my new task >> todo.txt` and if i run this on Linux i would expect the file to be converted to use \n and if i run it on Windows i would expect it to be converted to "\r\n".

But i would also understand when it preserves the first occuring newline separator.

**Comment by vonshednob** [comment]
Perfect! Thank you so much for your contribution!

**Pull request merged**
