### PR TITLE
lift hardcoded values to support subclassing

### PR DESCRIPTION
**Pull request by seanbreckenridge**
- use class lookups in Task to allow overriding constants
- let user pass task_class to TodoTxt
- make sure excluded attribute keys are included in bare_description

Added some examples to the tests to show how this may be used

Also, maybe `python_requires` in `setup.py` should be bumped to `3.6`? Since this uses f-strings, it wouldn't work on versions before that

### CODE REVIEW

**Comment by vonshednob** [comment]
Excellent design choice to make `Task` exchangeable!

Also, I fully agree with leaving URLs in the `bare_description`; a clear oversight from my side.

I’ll also take care of the python version bump; thanks for pointing it out.

Once more: thanks a lot for your big contribution!

**Comment by Sylvain303** [comment]
Hi,

Curiously I'm hacking this code at the same time. :smile: 
I would like to separate `parse()` in to two adding  `parse_from_lines()` I merged into support-subclassing branch from this PR. (I will do a separate PR of course if you think it could be useful)


```python
    def parse_from_lines(self, lines, filter_func=None):
        """(Re)parse an input from list of line of text
        used by parse()
        filter_func: an optional function or method to get str from
                     if lines contain more complex object.
        """
        self.tasks = []

        # read lines and parse them as tasks
        for linenr, line in enumerate(lines):
            if callable(filter_func):
                line = filter_func(line)

            if len(line.strip()) == 0:
                continue
            task = self.task_class(line, linenr=linenr, todotxt=self)
            self.tasks.append(task)

        return self.tasks
``` 

I don't think it could be achieved by sub-classing in this case?

 My use-case:

the todo.txt `lines` are stored into a page in a Zim wiki txt file. Extracted first, then manipulated as `Task` and wrote back embedded into the page section.

**Comment by vonshednob** [comment]
@Sylvain303 looks like @seanbreckenridge solves your problem right there. With this PR you could just subclass your own `Task` type and extend `Task.parse` something like this:

```python
import pytodotxt

class MyTask(pytodotxt.Task):
    def parse(self, line):
        # do stuff to 'line'
        super().parse(line)

todotxt = pytodotxt.TodoTxt("todo.txt", task_class=MyTask)
```

**Comment by Sylvain303** [comment]
@vonshednob oh interesting, let me try that. 

I'm missing a setter too: I added a `Task.set_completed()`.
Is it on purpose that there's no modification method?
Or did I miss some python trick?

It also appears I need to add a task after parsing, `TodoTxt.add_task()` to append to `Tasks.tasks` list.

https://github.com/Sylvain303/pytodotxt/blob/support-subclassing/pytodotxt/todotxt.py#L70

Let me also try if I can sub-class for that too.

Thanks for you hint.

Actually I'm doing (at top level) it's a prototype actually `ZimPage_todotxt` is a class of mine I'm crafting.

```python
zim_todotxt = ZimPage_todotxt(zim_notebook, zim_page)
print(f"zim: {zim_todotxt.get_zim_filename()}")
todos_zim_lines = zim_todotxt.get_todo_from_zimpage(zim_section_name)

# giving a filename here is not used, only for comparing and debugging purpose
# the output will also go into the Zim page at the end 
todotxt_zim = pytodotxt.TodoTxt('zimtodo.txt')
# create the todo list from seeded with Zim's page extracted lines
todotxt_zim.parse_from_lines(todos_zim_lines)
todotxt_zim.add_task("new tasks")

print(f"================== parse_from_lines todotxt_zim list not completed: {len(todotxt_zim.tasks)}")
for t in todotxt_zim.tasks:
    if not t.is_completed:
        print(f"{t.linenr}: {t.description}")

    if 'multiprises atelier' in t.description:
        t.set_completed()
        print(f"set_completed: {t.linenr}")

# deletion of item is also handled replacing section with shorter updated input 
#del todotxt_zim.tasks[-1]
zim_todotxt.save_todos_into_zimpage(zim_section_name, todotxt_zim)
```

**Comment by vonshednob** [comment]
> I'm missing a setter too: I added a `Task.set_completed()`. Is it on purpose that there's no modification method? Or did I miss some python trick?

No, you’re not missing anything; it’s rather that the documentation is really not as good as it should be (nor are the examples).

The way to mark a task as completed is as simple as `task.is_completed = True`.


> It also appears I need to add a task after parsing, `TodoTxt.add_task()` to append to `Tasks.tasks` list.

Not quite sure I get what you mean; `TodoTxt.parse` or `Task.parse`?

The general idea was to have `Task` only very loosely coupled to a `TodoTxt`, that’s why `Task.todotxt` can be `None`.

And in that regard adding a `Task` instance to `TodoTxt` would be as simple as `todotxt.tasks.append(task)`. Yes, in that case there’s no direct connection between `task` and `todotxt` from the perspective of `task`; but if the developer (you!) need that, I agree, a `add_task` function would be pretty useful.

Regarding the `ZimPage` example, it sounds to me like you’d like to have a parser that accepts a string as such (or even just a file handle) to read from, instead of only accepting a filename. Did I understand that right?

**Comment by vonshednob** [comment]
@seanbreckenridge after merging, but before releasing a new version I would probably refactor the code in general to split the parser from the container, i.e. turn `TodoTxt` into a container only, and have a separate `TodoTxtParser`.

That would mean that the `task_class` parameter would be moved to the parser. What do you think?

It’s a potentially API breaking change :thinking:

**Comment by Sylvain303** [comment]
> > [ missing a setter too:  `Task.set_completed()` ]

> No, you’re not missing anything; it’s rather that the documentation is really not as good as it should be (nor are the examples).
> 
> The way to mark a task as completed is as simple as `task.is_completed = True`.

Oh I see, I did not understood the loose coupling and was using the `TodoTxt` as a container.
Especial if I use @seanbreckenridge `task_class` new feature to pass my own class to handle more behavior.

Code sample bellow with sub-classing of Task as you suggested:

https://github.com/Sylvain303/tototxt_zim/blob/main/extended_todotxt_task.py

Here's the setter code I wrote (with coupling detection and update) I'm not sure if `linenr` is a list index or an input file line-1 ref. but it works actually.
```python
    def set_completed(self, completed=True, completion_date=None):
        self.is_completed = completed

        if completion_date is not None:
            self.completion_date = completion_date

        # update parent item in tasks[]
        if self.todotxt and self.linenr and self == self.todotxt.tasks[self.linenr]:
            self.todotxt.tasks[self.linenr].is_completed = self.is_completed
            self.todotxt.tasks[self.linenr].completion_date = self.completion_date
```

> > It also appears I need to add a task after parsing, `TodoTxt.add_task()` to append to ~~`Tasks.tasks`~~ list.
> 
> Not quite sure I get what you mean; `TodoTxt.parse` or `Task.parse`?
>

Oh, sorry made a mistake: `TodoTxt.tasks` list. I mean adding new task to the container. As I can set the Task class with `task_class=ZimTask` the `add_task()` method also keep it, right? (in my code it did obviously :wink: )
 
> Regarding the `ZimPage` example, it sounds to me like you’d like to have a parser that accepts a string as such (or even just a file handle) to read from, instead of only accepting a filename. Did I understand that right?

Oh yes, the fact is that `TodoTxt.parse()` only works on filename limits me in my use-case. That's why I have to introduce [TodoTxt.parse_from_lines](https://github.com/Sylvain303/tototxt_zim/blob/main/extended_todotxt_todotxt.py#L15). 

My idea was: just move out the loop on line's code from `TodoTxt.parse()`, and make a method to only call that loop directly, without the file read lines strip. A io reader or file handle could simplify the way to alter the source input from `TodoTxt`, that's true. I was thinking to write a `/dev/shm` file, but I feel its become too hacky/dirty for just a list(str). :wink: 

I did try to sub-class `TodoTxt` but that's introduce a lot of code duplication, code reuse is mostly lost.

[My subclass attempt of TodoTxt](https://github.com/Sylvain303/tototxt_zim/blob/main/extended_todotxt_todotxt.py)  

Zim page toto.txt extraction is actually done [here](https://github.com/Sylvain303/tototxt_zim/blob/main/todotxt.py#L31). It becomes a bit more complex, as I'm switching my code to sub-classing or not.

A Zim section page look like:

```
===== Todo section =====
[ ] write python wrapper to modify this todo by script
[ ] select the good todo.txt python's lib
[ ] have fun
[*] task containing "finish him" will be completed
[ ] nouvelle tasks
``` 

I uploaded a sample [here](https://github.com/Sylvain303/tototxt_zim/blob/main/Notebooks/Notes/knowledge/todo.txt/sample_todo_list.txt) of Zim page.

**Pull request merged**
